source 'http://rubygems.org'

gem 'rails', '3.0.0.beta4'
gem 'haml'
gem 'sequel'
gem 'pg'
gem 'dm-types'
gem 'dm-migrations'
gem 'dm-is-list'
gem 'dm-postgres-adapter'
gem 'data_objects'
gem 'typhoeus'
gem 'brewery'
gem 'rspec-rails', '>= 2.0.0.beta.12'
