source 'http://rubygems.org'

gem 'rails', '3.0.0.rc'
gem 'haml'
gem 'sequel'
gem 'pg'
gem 'dm-types'
gem 'dm-migrations'
gem 'dm-is-list'
gem 'dm-postgres-adapter'
gem 'data_objects'
gem 'typhoeus'
gem 'brewery', :git => 'http://github.com/Stiivi/brewery.git'
gem 'RedCloth'
