palettes:
  default:
    colors: &default_colors
      - F2DC55
      - 609A47
      - 4A71A8
      - 77673D
      - DB6631
      - 6E7466
      - C13353
      - FCFBA6
      - ACCF90
      - B8C7D7
      - BBA67E
      - EEAC7B
      - B6B6AA
      - DFA4A9
      - EBB713
      - 246F09
      - 1C458D
      - 322602
      - D34015
      - 424D43
      - AD0027
      - F5E56C
      - 85B46A
      - 7E9BBA
      - 8E7D57
      - E38858
      - 8B8F81
      - D26D7C
    specific_colors:
      ostatne: "eaeaea"
  druh_postupu:
    colors: *default_colors
    specific_colors:
      verejna: "56a736"
      bez: d84409
      uzsia: e4811e
      unknown: "424242"
      dialog: "f2dc55"
      new: "979797"
      so: 46892c
  apple:
    colors: &default_colors
      - 446a9c
      - 72a65b
      - e8b152
      - c44142
      - 824f8c
      - 6f8eb8
      - 94bf82
      - eec682
      - d37172
      - a478ad
      - 597caa
      - 82b26e
      - ebbb6a
      - cb585a
      - 93639c
    specific_colors:
      ostatne: "eaeaea"
      