palettes:
  default:
    colors: &default_colors
      - FCFBA6
      - ACCF90
      - B8C7D7
      - BBA67E
      - EEAC7B
      - B6B6AA
      - DFA4A9
      - F2DC55
      - 609A47
      - 4A71A8
      - 77673D
      - DB6631
      - 6E7466
      - C13353
      - EBB713
      - 246F09
      - 1C458D
      - 322602
      - D34015
      - 424D43
      - AD0027
      - F5E56C
      - 85B46A
      - 7E9BBA
      - 8E7D57
      - E38858
      - 8B8F81
      - D26D7C
    specific_colors:
      ostatne: "B6B6AA"
  druh_postupu:
    colors: *default_colors
    specific_colors:
      verejná súťaž: 56a736
      rokovacie konanie bez zverejnenia: d84409
      užšia súťaž: d87409
      "*unknown": "979797"
      rokovacie konanie so zverejnením: 46892c